export const SUCCESSFUL_REGISTRATION = 'SUCCESSFUL_REGISTRATION';
export const WRONG_REGISTRATION = 'WRONG_REGISTRATION';
export const SUCCESSFUL_LOGIN = 'SUCCESSFUL_LOGIN';
export const WRONG_LOGIN = 'WRONG_LOGIN';
export const SET_AUTHENTICATED_USER = 'SET_AUTHENTICATED_USER';
export const LOG_OUT = 'LOG_OUT';

export const FILE_UPLOAD = 'FILE_UPLOAD';
export const SUCCESSFUL_FILE_UPLOAD = 'SUCCESSFUL_FILE_UPLOAD';
export const WRONG_FILE_UPLOAD = 'WRONG_FILE_UPLOAD';
export const SUCCESSFUL_LINK_CREATION = 'SUCCESSFUL_LINK_CREATION';
export const WRONG_LINK_CREATION = 'WRONG_LINK_CREATION';
export const SHOW_ALERT = 'SHOW_ALERT';

export const CLEAN_ALERT = 'CLEAN_ALERT';
